# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Repaso_VIVADO/ARTYZ720.xdc

# Block Designs: bd/custom_Ip_design/custom_Ip_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==custom_Ip_design || ORIG_REF_NAME==custom_Ip_design} -quiet] -quiet

# IP: bd/custom_Ip_design/ip/custom_Ip_design_processing_system7_0_0/custom_Ip_design_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==custom_Ip_design_processing_system7_0_0 || ORIG_REF_NAME==custom_Ip_design_processing_system7_0_0} -quiet] -quiet

# IP: bd/custom_Ip_design/ip/custom_Ip_design_FirstIP_PWM_0_0/custom_Ip_design_FirstIP_PWM_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==custom_Ip_design_FirstIP_PWM_0_0 || ORIG_REF_NAME==custom_Ip_design_FirstIP_PWM_0_0} -quiet] -quiet

# IP: bd/custom_Ip_design/ip/custom_Ip_design_auto_pc_0/custom_Ip_design_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==custom_Ip_design_auto_pc_0 || ORIG_REF_NAME==custom_Ip_design_auto_pc_0} -quiet] -quiet

# IP: bd/custom_Ip_design/ip/custom_Ip_design_ps7_0_axi_periph_0/custom_Ip_design_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==custom_Ip_design_ps7_0_axi_periph_0 || ORIG_REF_NAME==custom_Ip_design_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/custom_Ip_design/ip/custom_Ip_design_rst_ps7_0_100M_0/custom_Ip_design_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==custom_Ip_design_rst_ps7_0_100M_0 || ORIG_REF_NAME==custom_Ip_design_rst_ps7_0_100M_0} -quiet] -quiet

# XDC: bd/custom_Ip_design/custom_Ip_design_ooc.xdc
