# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/danie/Documents/Repaso_VIVADO/PYNQ_base/base/base.srcs/sources_1/bd/base/ip/base_s00_regslice_22/base_s00_regslice_22.xci
# IP: The module: 'base_s00_regslice_22' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/danie/Documents/Repaso_VIVADO/PYNQ_base/base/base.srcs/sources_1/bd/base/ip/base_s00_regslice_22/base_s00_regslice_22_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_s00_regslice_22'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/danie/Documents/Repaso_VIVADO/PYNQ_base/base/base.srcs/sources_1/bd/base/ip/base_s00_regslice_22/base_s00_regslice_22_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_s00_regslice_22'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Users/danie/Documents/Repaso_VIVADO/PYNQ_base/base/base.srcs/sources_1/bd/base/ip/base_s00_regslice_22/base_s00_regslice_22.xci
# IP: The module: 'base_s00_regslice_22' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/danie/Documents/Repaso_VIVADO/PYNQ_base/base/base.srcs/sources_1/bd/base/ip/base_s00_regslice_22/base_s00_regslice_22_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_s00_regslice_22'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/danie/Documents/Repaso_VIVADO/PYNQ_base/base/base.srcs/sources_1/bd/base/ip/base_s00_regslice_22/base_s00_regslice_22_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_s00_regslice_22'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
