# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/comblock_fifo/comblock_fifo.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==comblock_fifo || ORIG_REF_NAME==comblock_fifo} -quiet] -quiet

# IP: bd/comblock_fifo/ip/comblock_fifo_processing_system7_0_0/comblock_fifo_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==comblock_fifo_processing_system7_0_0 || ORIG_REF_NAME==comblock_fifo_processing_system7_0_0} -quiet] -quiet

# IP: bd/comblock_fifo/ip/comblock_fifo_comblock_0_0/comblock_fifo_comblock_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==comblock_fifo_comblock_0_0 || ORIG_REF_NAME==comblock_fifo_comblock_0_0} -quiet] -quiet

# IP: bd/comblock_fifo/ip/comblock_fifo_xbar_0/comblock_fifo_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==comblock_fifo_xbar_0 || ORIG_REF_NAME==comblock_fifo_xbar_0} -quiet] -quiet

# IP: bd/comblock_fifo/ip/comblock_fifo_ps7_0_axi_periph_0/comblock_fifo_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==comblock_fifo_ps7_0_axi_periph_0 || ORIG_REF_NAME==comblock_fifo_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/comblock_fifo/ip/comblock_fifo_rst_ps7_0_100M_0/comblock_fifo_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==comblock_fifo_rst_ps7_0_100M_0 || ORIG_REF_NAME==comblock_fifo_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/comblock_fifo/ip/comblock_fifo_xlconstant_0_0/comblock_fifo_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==comblock_fifo_xlconstant_0_0 || ORIG_REF_NAME==comblock_fifo_xlconstant_0_0} -quiet] -quiet

# IP: bd/comblock_fifo/ip/comblock_fifo_xlconstant_1_0/comblock_fifo_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==comblock_fifo_xlconstant_1_0 || ORIG_REF_NAME==comblock_fifo_xlconstant_1_0} -quiet] -quiet

# IP: bd/comblock_fifo/ip/comblock_fifo_c_counter_binary_0_0/comblock_fifo_c_counter_binary_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==comblock_fifo_c_counter_binary_0_0 || ORIG_REF_NAME==comblock_fifo_c_counter_binary_0_0} -quiet] -quiet

# IP: bd/comblock_fifo/ip/comblock_fifo_auto_pc_1/comblock_fifo_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==comblock_fifo_auto_pc_1 || ORIG_REF_NAME==comblock_fifo_auto_pc_1} -quiet] -quiet

# IP: bd/comblock_fifo/ip/comblock_fifo_auto_pc_0/comblock_fifo_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==comblock_fifo_auto_pc_0 || ORIG_REF_NAME==comblock_fifo_auto_pc_0} -quiet] -quiet

# XDC: bd/comblock_fifo/comblock_fifo_ooc.xdc
