# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\REGS_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_RegisterGUI(object):
    def setupUi(self, RegisterGUI):
        RegisterGUI.setObjectName("RegisterGUI")
        RegisterGUI.resize(700, 449)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        RegisterGUI.setPalette(palette)
        self.centralwidget = QtWidgets.QWidget(RegisterGUI)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 681, 411))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.groupBox_OUTREGS = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBox_OUTREGS.setMinimumSize(QtCore.QSize(551, 141))
        self.groupBox_OUTREGS.setObjectName("groupBox_OUTREGS")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_OUTREGS)
        self.layoutWidget1.setGeometry(QtCore.QRect(90, 30, 421, 21))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.layoutWidget2 = QtWidgets.QWidget(self.groupBox_OUTREGS)
        self.layoutWidget2.setGeometry(QtCore.QRect(40, 60, 30, 71))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_on = QtWidgets.QLabel(self.layoutWidget2)
        self.label_on.setMinimumSize(QtCore.QSize(28, 25))
        self.label_on.setMaximumSize(QtCore.QSize(28, 25))
        self.label_on.setObjectName("label_on")
        self.verticalLayout.addWidget(self.label_on)
        self.label_off = QtWidgets.QLabel(self.layoutWidget2)
        self.label_off.setMinimumSize(QtCore.QSize(28, 25))
        self.label_off.setMaximumSize(QtCore.QSize(28, 25))
        self.label_off.setObjectName("label_off")
        self.verticalLayout.addWidget(self.label_off)
        self.layoutWidget3 = QtWidgets.QWidget(self.groupBox_OUTREGS)
        self.layoutWidget3.setGeometry(QtCore.QRect(80, 60, 431, 71))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sw3 = QtWidgets.QSlider(self.layoutWidget3)
        self.sw3.setMaximumSize(QtCore.QSize(22, 59))
        self.sw3.setMaximum(1)
        self.sw3.setTracking(True)
        self.sw3.setOrientation(QtCore.Qt.Vertical)
        self.sw3.setObjectName("sw3")
        self.horizontalLayout.addWidget(self.sw3)
        self.sw2 = QtWidgets.QSlider(self.layoutWidget3)
        self.sw2.setMaximumSize(QtCore.QSize(22, 59))
        self.sw2.setMaximum(1)
        self.sw2.setOrientation(QtCore.Qt.Vertical)
        self.sw2.setObjectName("sw2")
        self.horizontalLayout.addWidget(self.sw2)
        self.sw1 = QtWidgets.QSlider(self.layoutWidget3)
        self.sw1.setMaximumSize(QtCore.QSize(22, 59))
        self.sw1.setMaximum(1)
        self.sw1.setOrientation(QtCore.Qt.Vertical)
        self.sw1.setObjectName("sw1")
        self.horizontalLayout.addWidget(self.sw1)
        self.sw0 = QtWidgets.QSlider(self.layoutWidget3)
        self.sw0.setMaximumSize(QtCore.QSize(22, 59))
        self.sw0.setMaximum(1)
        self.sw0.setOrientation(QtCore.Qt.Vertical)
        self.sw0.setObjectName("sw0")
        self.horizontalLayout.addWidget(self.sw0)
        self.horizontalLayout_5.addWidget(self.groupBox_OUTREGS)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.groupBox_INREGS = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBox_INREGS.setMinimumSize(QtCore.QSize(541, 111))
        self.groupBox_INREGS.setObjectName("groupBox_INREGS")
        self.layoutWidget4 = QtWidgets.QWidget(self.groupBox_INREGS)
        self.layoutWidget4.setGeometry(QtCore.QRect(50, 40, 441, 61))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.led_indicator3 = QtWidgets.QLabel(self.layoutWidget4)
        self.led_indicator3.setText("")
        self.led_indicator3.setObjectName("led_indicator3")
        self.horizontalLayout_3.addWidget(self.led_indicator3)
        self.led_indicator2 = QtWidgets.QLabel(self.layoutWidget4)
        self.led_indicator2.setText("")
        self.led_indicator2.setObjectName("led_indicator2")
        self.horizontalLayout_3.addWidget(self.led_indicator2)
        self.led_indicator1 = QtWidgets.QLabel(self.layoutWidget4)
        self.led_indicator1.setText("")
        self.led_indicator1.setObjectName("led_indicator1")
        self.horizontalLayout_3.addWidget(self.led_indicator1)
        self.led_indicator0 = QtWidgets.QLabel(self.layoutWidget4)
        self.led_indicator0.setText("")
        self.led_indicator0.setObjectName("led_indicator0")
        self.horizontalLayout_3.addWidget(self.led_indicator0)
        self.horizontalLayout_6.addWidget(self.groupBox_INREGS)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        RegisterGUI.setCentralWidget(self.centralwidget)

        self.retranslateUi(RegisterGUI)
        QtCore.QMetaObject.connectSlotsByName(RegisterGUI)

    def retranslateUi(self, RegisterGUI):
        _translate = QtCore.QCoreApplication.translate
        RegisterGUI.setWindowTitle(_translate("RegisterGUI", "Register IN/OUT GUI"))
        self.label.setText(_translate("RegisterGUI", "<html><head/><body><p><span style=\" font-size:20pt; font-weight:600; color:#054ab0;\">IN/OUT REGISTERS GUI</span></p></body></html>"))
        self.groupBox_OUTREGS.setTitle(_translate("RegisterGUI", "OUT_REGS"))
        self.label_4.setText(_translate("RegisterGUI", "<html><head/><body><p align=\"center\">LED3</p></body></html>"))
        self.label_5.setText(_translate("RegisterGUI", "<html><head/><body><p align=\"center\">LED2</p></body></html>"))
        self.label_6.setText(_translate("RegisterGUI", "<html><head/><body><p align=\"center\">LED1</p></body></html>"))
        self.label_7.setText(_translate("RegisterGUI", "<html><head/><body><p align=\"center\">LED0</p></body></html>"))
        self.label_on.setText(_translate("RegisterGUI", "ON"))
        self.label_off.setText(_translate("RegisterGUI", "OFF"))
        self.groupBox_INREGS.setTitle(_translate("RegisterGUI", "IN_REGS"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RegisterGUI = QtWidgets.QMainWindow()
    ui = Ui_RegisterGUI()
    ui.setupUi(RegisterGUI)
    RegisterGUI.show()
    sys.exit(app.exec_())

