# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Implementaciones_FPGA/ARTYZ720.xdc

# Block Designs: bd/prueba_comblock2/prueba_comblock2.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prueba_comblock2 || ORIG_REF_NAME==prueba_comblock2} -quiet] -quiet

# IP: bd/prueba_comblock2/ip/prueba_comblock2_processing_system7_0_0/prueba_comblock2_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prueba_comblock2_processing_system7_0_0 || ORIG_REF_NAME==prueba_comblock2_processing_system7_0_0} -quiet] -quiet

# IP: bd/prueba_comblock2/ip/prueba_comblock2_comblock_0_0/prueba_comblock2_comblock_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prueba_comblock2_comblock_0_0 || ORIG_REF_NAME==prueba_comblock2_comblock_0_0} -quiet] -quiet

# IP: bd/prueba_comblock2/ip/prueba_comblock2_xbar_0/prueba_comblock2_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prueba_comblock2_xbar_0 || ORIG_REF_NAME==prueba_comblock2_xbar_0} -quiet] -quiet

# IP: bd/prueba_comblock2/ip/prueba_comblock2_ps7_0_axi_periph_0/prueba_comblock2_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prueba_comblock2_ps7_0_axi_periph_0 || ORIG_REF_NAME==prueba_comblock2_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/prueba_comblock2/ip/prueba_comblock2_rst_ps7_0_100M_0/prueba_comblock2_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prueba_comblock2_rst_ps7_0_100M_0 || ORIG_REF_NAME==prueba_comblock2_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/prueba_comblock2/ip/prueba_comblock2_Generator_uartContro_0_0/prueba_comblock2_Generator_uartContro_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prueba_comblock2_Generator_uartContro_0_0 || ORIG_REF_NAME==prueba_comblock2_Generator_uartContro_0_0} -quiet] -quiet

# IP: bd/prueba_comblock2/ip/prueba_comblock2_Transmitter_0_0/prueba_comblock2_Transmitter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prueba_comblock2_Transmitter_0_0 || ORIG_REF_NAME==prueba_comblock2_Transmitter_0_0} -quiet] -quiet

# IP: bd/prueba_comblock2/ip/prueba_comblock2_xlconcat_0_0/prueba_comblock2_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prueba_comblock2_xlconcat_0_0 || ORIG_REF_NAME==prueba_comblock2_xlconcat_0_0} -quiet] -quiet

# IP: bd/prueba_comblock2/ip/prueba_comblock2_xlconstant_0_0/prueba_comblock2_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prueba_comblock2_xlconstant_0_0 || ORIG_REF_NAME==prueba_comblock2_xlconstant_0_0} -quiet] -quiet

# IP: bd/prueba_comblock2/ip/prueba_comblock2_Receiver_0_0/prueba_comblock2_Receiver_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prueba_comblock2_Receiver_0_0 || ORIG_REF_NAME==prueba_comblock2_Receiver_0_0} -quiet] -quiet

# IP: bd/prueba_comblock2/ip/prueba_comblock2_xlslice_0_0/prueba_comblock2_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prueba_comblock2_xlslice_0_0 || ORIG_REF_NAME==prueba_comblock2_xlslice_0_0} -quiet] -quiet

# IP: bd/prueba_comblock2/ip/prueba_comblock2_xlconstant_1_0/prueba_comblock2_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prueba_comblock2_xlconstant_1_0 || ORIG_REF_NAME==prueba_comblock2_xlconstant_1_0} -quiet] -quiet

# IP: bd/prueba_comblock2/ip/prueba_comblock2_xlconstant_2_0/prueba_comblock2_xlconstant_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prueba_comblock2_xlconstant_2_0 || ORIG_REF_NAME==prueba_comblock2_xlconstant_2_0} -quiet] -quiet

# IP: bd/prueba_comblock2/ip/prueba_comblock2_negation_0_0/prueba_comblock2_negation_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prueba_comblock2_negation_0_0 || ORIG_REF_NAME==prueba_comblock2_negation_0_0} -quiet] -quiet

# IP: bd/prueba_comblock2/ip/prueba_comblock2_auto_pc_1/prueba_comblock2_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prueba_comblock2_auto_pc_1 || ORIG_REF_NAME==prueba_comblock2_auto_pc_1} -quiet] -quiet

# IP: bd/prueba_comblock2/ip/prueba_comblock2_auto_pc_0/prueba_comblock2_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prueba_comblock2_auto_pc_0 || ORIG_REF_NAME==prueba_comblock2_auto_pc_0} -quiet] -quiet

# XDC: bd/prueba_comblock2/prueba_comblock2_ooc.xdc
