# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Repaso_VIVADO/ARTYZ720.xdc

# Block Designs: bd/customIp2/customIp2.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==customIp2 || ORIG_REF_NAME==customIp2} -quiet] -quiet

# IP: bd/customIp2/ip/customIp2_processing_system7_0_0/customIp2_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==customIp2_processing_system7_0_0 || ORIG_REF_NAME==customIp2_processing_system7_0_0} -quiet] -quiet

# IP: bd/customIp2/ip/customIp2_SecondIP_PWM_0_0/customIp2_SecondIP_PWM_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==customIp2_SecondIP_PWM_0_0 || ORIG_REF_NAME==customIp2_SecondIP_PWM_0_0} -quiet] -quiet

# IP: bd/customIp2/ip/customIp2_ps7_0_axi_periph_0/customIp2_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==customIp2_ps7_0_axi_periph_0 || ORIG_REF_NAME==customIp2_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/customIp2/ip/customIp2_rst_ps7_0_100M_0/customIp2_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==customIp2_rst_ps7_0_100M_0 || ORIG_REF_NAME==customIp2_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/customIp2/ip/customIp2_auto_pc_0/customIp2_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==customIp2_auto_pc_0 || ORIG_REF_NAME==customIp2_auto_pc_0} -quiet] -quiet

# XDC: bd/customIp2/customIp2_ooc.xdc
