# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Repaso_VIVADO/ARTYZ720.xdc

# Block Designs: bd/Comblock_desing/Comblock_desing.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Comblock_desing || ORIG_REF_NAME==Comblock_desing} -quiet] -quiet

# IP: bd/Comblock_desing/ip/Comblock_desing_processing_system7_0_0/Comblock_desing_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Comblock_desing_processing_system7_0_0 || ORIG_REF_NAME==Comblock_desing_processing_system7_0_0} -quiet] -quiet

# IP: bd/Comblock_desing/ip/Comblock_desing_comblock_0_0/Comblock_desing_comblock_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Comblock_desing_comblock_0_0 || ORIG_REF_NAME==Comblock_desing_comblock_0_0} -quiet] -quiet

# IP: bd/Comblock_desing/ip/Comblock_desing_c_counter_binary_0_0/Comblock_desing_c_counter_binary_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Comblock_desing_c_counter_binary_0_0 || ORIG_REF_NAME==Comblock_desing_c_counter_binary_0_0} -quiet] -quiet

# IP: bd/Comblock_desing/ip/Comblock_desing_c_counter_binary_1_0/Comblock_desing_c_counter_binary_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Comblock_desing_c_counter_binary_1_0 || ORIG_REF_NAME==Comblock_desing_c_counter_binary_1_0} -quiet] -quiet

# IP: bd/Comblock_desing/ip/Comblock_desing_xlconstant_0_0/Comblock_desing_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Comblock_desing_xlconstant_0_0 || ORIG_REF_NAME==Comblock_desing_xlconstant_0_0} -quiet] -quiet

# IP: bd/Comblock_desing/ip/Comblock_desing_xlconstant_1_0/Comblock_desing_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Comblock_desing_xlconstant_1_0 || ORIG_REF_NAME==Comblock_desing_xlconstant_1_0} -quiet] -quiet

# IP: bd/Comblock_desing/ip/Comblock_desing_xbar_0/Comblock_desing_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Comblock_desing_xbar_0 || ORIG_REF_NAME==Comblock_desing_xbar_0} -quiet] -quiet

# IP: bd/Comblock_desing/ip/Comblock_desing_auto_pc_1/Comblock_desing_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Comblock_desing_auto_pc_1 || ORIG_REF_NAME==Comblock_desing_auto_pc_1} -quiet] -quiet

# IP: bd/Comblock_desing/ip/Comblock_desing_auto_pc_0/Comblock_desing_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Comblock_desing_auto_pc_0 || ORIG_REF_NAME==Comblock_desing_auto_pc_0} -quiet] -quiet

# IP: bd/Comblock_desing/ip/Comblock_desing_ps7_0_axi_periph_0/Comblock_desing_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Comblock_desing_ps7_0_axi_periph_0 || ORIG_REF_NAME==Comblock_desing_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/Comblock_desing/ip/Comblock_desing_rst_ps7_0_100M_0/Comblock_desing_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Comblock_desing_rst_ps7_0_100M_0 || ORIG_REF_NAME==Comblock_desing_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/Comblock_desing/ip/Comblock_desing_xlconcat_0_0/Comblock_desing_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Comblock_desing_xlconcat_0_0 || ORIG_REF_NAME==Comblock_desing_xlconcat_0_0} -quiet] -quiet

# IP: bd/Comblock_desing/ip/Comblock_desing_xlconstant_2_0/Comblock_desing_xlconstant_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Comblock_desing_xlconstant_2_0 || ORIG_REF_NAME==Comblock_desing_xlconstant_2_0} -quiet] -quiet

# XDC: bd/Comblock_desing/Comblock_desing_ooc.xdc
