# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/danie/Documents/Implementaciones_FPGA/PYNQ/comunication_with_comblock2/comunication_with_comblock2.srcs/sources_1/bd/prueba_comblock2/ip/prueba_comblock2_rst_ps7_0_100M_0/prueba_comblock2_rst_ps7_0_100M_0.xci
# IP: The module: 'prueba_comblock2_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/danie/Documents/Implementaciones_FPGA/PYNQ/comunication_with_comblock2/comunication_with_comblock2.srcs/sources_1/bd/prueba_comblock2/ip/prueba_comblock2_rst_ps7_0_100M_0/prueba_comblock2_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'prueba_comblock2_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/danie/Documents/Implementaciones_FPGA/PYNQ/comunication_with_comblock2/comunication_with_comblock2.srcs/sources_1/bd/prueba_comblock2/ip/prueba_comblock2_rst_ps7_0_100M_0/prueba_comblock2_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'prueba_comblock2_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/danie/Documents/Implementaciones_FPGA/PYNQ/comunication_with_comblock2/comunication_with_comblock2.srcs/sources_1/bd/prueba_comblock2/ip/prueba_comblock2_rst_ps7_0_100M_0/prueba_comblock2_rst_ps7_0_100M_0.xci
# IP: The module: 'prueba_comblock2_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/danie/Documents/Implementaciones_FPGA/PYNQ/comunication_with_comblock2/comunication_with_comblock2.srcs/sources_1/bd/prueba_comblock2/ip/prueba_comblock2_rst_ps7_0_100M_0/prueba_comblock2_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'prueba_comblock2_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/danie/Documents/Implementaciones_FPGA/PYNQ/comunication_with_comblock2/comunication_with_comblock2.srcs/sources_1/bd/prueba_comblock2/ip/prueba_comblock2_rst_ps7_0_100M_0/prueba_comblock2_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'prueba_comblock2_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
