# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Repaso_VIVADO/ARTYZ720.xdc

# Block Designs: bd/emio_desing/emio_desing.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==emio_desing || ORIG_REF_NAME==emio_desing} -quiet] -quiet

# IP: bd/emio_desing/ip/emio_desing_processing_system7_0_0/emio_desing_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==emio_desing_processing_system7_0_0 || ORIG_REF_NAME==emio_desing_processing_system7_0_0} -quiet] -quiet

# XDC: bd/emio_desing/emio_desing_ooc.xdc
