# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/danie/Documents/Repaso_VIVADO/PYNQ_base/base/base.srcs/sources_1/bd/base/ip/base_auto_pc_4/base_auto_pc_4.xci
# IP: The module: 'base_auto_pc_4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/danie/Documents/Repaso_VIVADO/PYNQ_base/base/base.srcs/sources_1/bd/base/ip/base_auto_pc_4/base_auto_pc_4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_auto_pc_4'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/danie/Documents/Repaso_VIVADO/PYNQ_base/base/base.srcs/sources_1/bd/base/ip/base_auto_pc_4/base_auto_pc_4.xci
# IP: The module: 'base_auto_pc_4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/danie/Documents/Repaso_VIVADO/PYNQ_base/base/base.srcs/sources_1/bd/base/ip/base_auto_pc_4/base_auto_pc_4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_auto_pc_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
