# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/led_control_desing/led_control_desing.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==led_control_desing || ORIG_REF_NAME==led_control_desing} -quiet] -quiet

# IP: bd/led_control_desing/ip/led_control_desing_processing_system7_0_0/led_control_desing_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==led_control_desing_processing_system7_0_0 || ORIG_REF_NAME==led_control_desing_processing_system7_0_0} -quiet] -quiet

# IP: bd/led_control_desing/ip/led_control_desing_axi_gpio_0_0/led_control_desing_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==led_control_desing_axi_gpio_0_0 || ORIG_REF_NAME==led_control_desing_axi_gpio_0_0} -quiet] -quiet

# IP: bd/led_control_desing/ip/led_control_desing_xbar_0/led_control_desing_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==led_control_desing_xbar_0 || ORIG_REF_NAME==led_control_desing_xbar_0} -quiet] -quiet

# IP: bd/led_control_desing/ip/led_control_desing_auto_pc_0/led_control_desing_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==led_control_desing_auto_pc_0 || ORIG_REF_NAME==led_control_desing_auto_pc_0} -quiet] -quiet

# IP: bd/led_control_desing/ip/led_control_desing_ps7_0_axi_periph_0/led_control_desing_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==led_control_desing_ps7_0_axi_periph_0 || ORIG_REF_NAME==led_control_desing_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/led_control_desing/ip/led_control_desing_rst_ps7_0_100M_0/led_control_desing_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==led_control_desing_rst_ps7_0_100M_0 || ORIG_REF_NAME==led_control_desing_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/led_control_desing/ip/led_control_desing_axi_gpio_0_1/led_control_desing_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==led_control_desing_axi_gpio_0_1 || ORIG_REF_NAME==led_control_desing_axi_gpio_0_1} -quiet] -quiet

# XDC: bd/led_control_desing/led_control_desing_ooc.xdc
