# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Implementaciones_FPGA/ARTYZ720.xdc

# Block Designs: bd/prueba_comblocl/prueba_comblocl.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prueba_comblocl || ORIG_REF_NAME==prueba_comblocl} -quiet] -quiet

# IP: bd/prueba_comblocl/ip/prueba_comblocl_processing_system7_0_0/prueba_comblocl_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prueba_comblocl_processing_system7_0_0 || ORIG_REF_NAME==prueba_comblocl_processing_system7_0_0} -quiet] -quiet

# IP: bd/prueba_comblocl/ip/prueba_comblocl_comblock_0_0/prueba_comblocl_comblock_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prueba_comblocl_comblock_0_0 || ORIG_REF_NAME==prueba_comblocl_comblock_0_0} -quiet] -quiet

# IP: bd/prueba_comblocl/ip/prueba_comblocl_xbar_0/prueba_comblocl_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prueba_comblocl_xbar_0 || ORIG_REF_NAME==prueba_comblocl_xbar_0} -quiet] -quiet

# IP: bd/prueba_comblocl/ip/prueba_comblocl_ps7_0_axi_periph_0/prueba_comblocl_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prueba_comblocl_ps7_0_axi_periph_0 || ORIG_REF_NAME==prueba_comblocl_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/prueba_comblocl/ip/prueba_comblocl_rst_ps7_0_100M_0/prueba_comblocl_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prueba_comblocl_rst_ps7_0_100M_0 || ORIG_REF_NAME==prueba_comblocl_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/prueba_comblocl/ip/prueba_comblocl_Transmitter_0_0/prueba_comblocl_Transmitter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prueba_comblocl_Transmitter_0_0 || ORIG_REF_NAME==prueba_comblocl_Transmitter_0_0} -quiet] -quiet

# IP: bd/prueba_comblocl/ip/prueba_comblocl_Receiver_0_0/prueba_comblocl_Receiver_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prueba_comblocl_Receiver_0_0 || ORIG_REF_NAME==prueba_comblocl_Receiver_0_0} -quiet] -quiet

# IP: bd/prueba_comblocl/ip/prueba_comblocl_auto_pc_1/prueba_comblocl_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prueba_comblocl_auto_pc_1 || ORIG_REF_NAME==prueba_comblocl_auto_pc_1} -quiet] -quiet

# IP: bd/prueba_comblocl/ip/prueba_comblocl_auto_pc_0/prueba_comblocl_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prueba_comblocl_auto_pc_0 || ORIG_REF_NAME==prueba_comblocl_auto_pc_0} -quiet] -quiet

# XDC: bd/prueba_comblocl/prueba_comblocl_ooc.xdc
