# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/danie/Documents/Repaso_VIVADO/PYNQ_base/base/base.srcs/sources_1/bd/base/ip/base_m00_regslice_18/base_m00_regslice_18.xci
# IP: The module: 'base_m00_regslice_18' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/danie/Documents/Repaso_VIVADO/PYNQ_base/base/base.srcs/sources_1/bd/base/ip/base_m00_regslice_18/base_m00_regslice_18_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_m00_regslice_18'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/danie/Documents/Repaso_VIVADO/PYNQ_base/base/base.srcs/sources_1/bd/base/ip/base_m00_regslice_18/base_m00_regslice_18_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_m00_regslice_18'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/danie/Documents/Repaso_VIVADO/PYNQ_base/base/base.srcs/sources_1/bd/base/ip/base_m00_regslice_18/base_m00_regslice_18.xci
# IP: The module: 'base_m00_regslice_18' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/danie/Documents/Repaso_VIVADO/PYNQ_base/base/base.srcs/sources_1/bd/base/ip/base_m00_regslice_18/base_m00_regslice_18_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_m00_regslice_18'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/danie/Documents/Repaso_VIVADO/PYNQ_base/base/base.srcs/sources_1/bd/base/ip/base_m00_regslice_18/base_m00_regslice_18_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_m00_regslice_18'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
