# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/danie/Documents/Implementaciones_FPGA/PYNQ/prueba_comblock/prueba_comblock.srcs/sources_1/bd/prueba_comblocl/ip/prueba_comblocl_xbar_0/prueba_comblocl_xbar_0.xci
# IP: The module: 'prueba_comblocl_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/danie/Documents/Implementaciones_FPGA/PYNQ/prueba_comblock/prueba_comblock.srcs/sources_1/bd/prueba_comblocl/ip/prueba_comblocl_xbar_0/prueba_comblocl_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'prueba_comblocl_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/danie/Documents/Implementaciones_FPGA/PYNQ/prueba_comblock/prueba_comblock.srcs/sources_1/bd/prueba_comblocl/ip/prueba_comblocl_xbar_0/prueba_comblocl_xbar_0.xci
# IP: The module: 'prueba_comblocl_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/danie/Documents/Implementaciones_FPGA/PYNQ/prueba_comblock/prueba_comblock.srcs/sources_1/bd/prueba_comblocl/ip/prueba_comblocl_xbar_0/prueba_comblocl_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'prueba_comblocl_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
