# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Repaso_VIVADO/ARTYZ720.xdc

# Block Designs: bd/comblock_desing/comblock_desing.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==comblock_desing || ORIG_REF_NAME==comblock_desing} -quiet] -quiet

# IP: bd/comblock_desing/ip/comblock_desing_comblock_0_0/comblock_desing_comblock_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==comblock_desing_comblock_0_0 || ORIG_REF_NAME==comblock_desing_comblock_0_0} -quiet] -quiet

# IP: bd/comblock_desing/ip/comblock_desing_processing_system7_0_0/comblock_desing_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==comblock_desing_processing_system7_0_0 || ORIG_REF_NAME==comblock_desing_processing_system7_0_0} -quiet] -quiet

# IP: bd/comblock_desing/ip/comblock_desing_xbar_0/comblock_desing_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==comblock_desing_xbar_0 || ORIG_REF_NAME==comblock_desing_xbar_0} -quiet] -quiet

# IP: bd/comblock_desing/ip/comblock_desing_ps7_0_axi_periph_0/comblock_desing_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==comblock_desing_ps7_0_axi_periph_0 || ORIG_REF_NAME==comblock_desing_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/comblock_desing/ip/comblock_desing_rst_ps7_0_100M_0/comblock_desing_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==comblock_desing_rst_ps7_0_100M_0 || ORIG_REF_NAME==comblock_desing_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/comblock_desing/ip/comblock_desing_xlconstant_0_0/comblock_desing_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==comblock_desing_xlconstant_0_0 || ORIG_REF_NAME==comblock_desing_xlconstant_0_0} -quiet] -quiet

# IP: bd/comblock_desing/ip/comblock_desing_xlconstant_1_0/comblock_desing_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==comblock_desing_xlconstant_1_0 || ORIG_REF_NAME==comblock_desing_xlconstant_1_0} -quiet] -quiet

# IP: bd/comblock_desing/ip/comblock_desing_xlconcat_0_0/comblock_desing_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==comblock_desing_xlconcat_0_0 || ORIG_REF_NAME==comblock_desing_xlconcat_0_0} -quiet] -quiet

# IP: bd/comblock_desing/ip/comblock_desing_xlconcat_0_1/comblock_desing_xlconcat_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==comblock_desing_xlconcat_0_1 || ORIG_REF_NAME==comblock_desing_xlconcat_0_1} -quiet] -quiet

# IP: bd/comblock_desing/ip/comblock_desing_xlconcat_0_2/comblock_desing_xlconcat_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==comblock_desing_xlconcat_0_2 || ORIG_REF_NAME==comblock_desing_xlconcat_0_2} -quiet] -quiet

# IP: bd/comblock_desing/ip/comblock_desing_xlconcat_0_3/comblock_desing_xlconcat_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==comblock_desing_xlconcat_0_3 || ORIG_REF_NAME==comblock_desing_xlconcat_0_3} -quiet] -quiet

# IP: bd/comblock_desing/ip/comblock_desing_xlconcat_0_4/comblock_desing_xlconcat_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==comblock_desing_xlconcat_0_4 || ORIG_REF_NAME==comblock_desing_xlconcat_0_4} -quiet] -quiet

# IP: bd/comblock_desing/ip/comblock_desing_auto_pc_1/comblock_desing_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==comblock_desing_auto_pc_1 || ORIG_REF_NAME==comblock_desing_auto_pc_1} -quiet] -quiet

# IP: bd/comblock_desing/ip/comblock_desing_auto_pc_0/comblock_desing_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==comblock_desing_auto_pc_0 || ORIG_REF_NAME==comblock_desing_auto_pc_0} -quiet] -quiet

# XDC: bd/comblock_desing/comblock_desing_ooc.xdc
