# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\VentanaSelectorDeFrecuencias.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SelectroDeFrecuencias(object):
    def setupUi(self, SelectroDeFrecuencias):
        SelectroDeFrecuencias.setObjectName("SelectroDeFrecuencias")
        SelectroDeFrecuencias.resize(445, 590)
        self.centralwidget = QtWidgets.QWidget(SelectroDeFrecuencias)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 10, 421, 531))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.entryFrecuencia = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.entryFrecuencia.setFont(font)
        self.entryFrecuencia.setObjectName("entryFrecuencia")
        self.horizontalLayout.addWidget(self.entryFrecuencia)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.labelEcho = QtWidgets.QLabel(self.widget)
        self.labelEcho.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.labelEcho.setObjectName("labelEcho")
        self.horizontalLayout_3.addWidget(self.labelEcho)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.button1hz = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button1hz.setFont(font)
        self.button1hz.setObjectName("button1hz")
        self.verticalLayout.addWidget(self.button1hz)
        self.button10hz = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button10hz.setFont(font)
        self.button10hz.setObjectName("button10hz")
        self.verticalLayout.addWidget(self.button10hz)
        self.button1khz = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button1khz.setFont(font)
        self.button1khz.setObjectName("button1khz")
        self.verticalLayout.addWidget(self.button1khz)
        self.button10khz = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button10khz.setFont(font)
        self.button10khz.setObjectName("button10khz")
        self.verticalLayout.addWidget(self.button10khz)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.LedIndicator = QtWidgets.QLabel(self.widget)
        self.LedIndicator.setMaximumSize(QtCore.QSize(41, 41))
        self.LedIndicator.setText("")
        self.LedIndicator.setObjectName("LedIndicator")
        self.horizontalLayout_2.addWidget(self.LedIndicator)
        self.buttonHabilitar = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.buttonHabilitar.setFont(font)
        self.buttonHabilitar.setObjectName("buttonHabilitar")
        self.horizontalLayout_2.addWidget(self.buttonHabilitar)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        SelectroDeFrecuencias.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(SelectroDeFrecuencias)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 445, 31))
        self.menuBar.setObjectName("menuBar")
        self.menuPuerto = QtWidgets.QMenu(self.menuBar)
        self.menuPuerto.setObjectName("menuPuerto")
        SelectroDeFrecuencias.setMenuBar(self.menuBar)
        self.actionPuerto = QtWidgets.QAction(SelectroDeFrecuencias)
        self.actionPuerto.setObjectName("actionPuerto")
        self.actionBaud = QtWidgets.QAction(SelectroDeFrecuencias)
        self.actionBaud.setObjectName("actionBaud")
        self.menuPuerto.addAction(self.actionPuerto)
        self.menuPuerto.addAction(self.actionBaud)
        self.menuBar.addAction(self.menuPuerto.menuAction())

        self.retranslateUi(SelectroDeFrecuencias)
        QtCore.QMetaObject.connectSlotsByName(SelectroDeFrecuencias)

    def retranslateUi(self, SelectroDeFrecuencias):
        _translate = QtCore.QCoreApplication.translate
        SelectroDeFrecuencias.setWindowTitle(_translate("SelectroDeFrecuencias", "Selector de frecuencias"))
        self.label.setText(_translate("SelectroDeFrecuencias", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600;\">Selector de </span></p><p align=\"center\"><span style=\" font-size:18pt; font-weight:600;\">Frecuencias</span></p></body></html>"))
        self.label_2.setText(_translate("SelectroDeFrecuencias", "<html><head/><body><p align=\"right\"><span style=\" font-size:16pt;\">Frecuencia (Hz):</span></p></body></html>"))
        self.labelEcho.setText(_translate("SelectroDeFrecuencias", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; color:#000000;\">Echo</span></p></body></html>"))
        self.button1hz.setText(_translate("SelectroDeFrecuencias", "1 Hz"))
        self.button10hz.setText(_translate("SelectroDeFrecuencias", "10 Hz"))
        self.button1khz.setText(_translate("SelectroDeFrecuencias", "1 KHz"))
        self.button10khz.setText(_translate("SelectroDeFrecuencias", "10 KHz"))
        self.buttonHabilitar.setText(_translate("SelectroDeFrecuencias", "Habilitar"))
        self.menuPuerto.setTitle(_translate("SelectroDeFrecuencias", "..."))
        self.actionPuerto.setText(_translate("SelectroDeFrecuencias", "Puerto"))
        self.actionBaud.setText(_translate("SelectroDeFrecuencias", "Baud"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SelectroDeFrecuencias = QtWidgets.QMainWindow()
    ui = Ui_SelectroDeFrecuencias()
    ui.setupUi(SelectroDeFrecuencias)
    SelectroDeFrecuencias.show()
    sys.exit(app.exec_())

